# Generated by Django 4.1.1 on 2023-01-09 20:08

from django.db import migrations, models
import verificacao.validator


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='Data_Admissao',
            field=models.DateTimeField(validators=[verificacao.validator.validate_data]),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='Hora_Admissao',
            field=models.TimeField(validators=[verificacao.validator.validate_hora]),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='Localizacao_Fisica',
            field=models.CharField(max_length=9, validators=[verificacao.validator.validate_localizacao]),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='Medico_Responsavel',
            field=models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits]),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='Numero_Prontuario',
            field=models.CharField(error_messages={'unique': 'Número de Prontuário já cadastrado, insira outro'}, max_length=5, unique=True, validators=[verificacao.validator.validate_numerodocumento, verificacao.validator.validate_digits]),
        ),
    ]
